import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Landing from "../components/landing";
import Aboutus from "../components/aboutus";
import Skills from "../components/skills";
import Works from "../components/works";
import TrustedBy from "../components/trustedby";
import ContactUs from "../components/contactus";
import Footer from "../components/footer";
import useSWR from "swr";

const fetcher = (input: any, init?: any) => {
  return fetch(input, init).then((res) => res.json());
};

const Home: NextPage = () => {
  const { data } = useSWR("/api/stats", fetcher);
  return (
    <div>
      <Head>
        <title>khao | company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <Aboutus />
      <Skills commits={data?.commits} />
      <Works />
      <TrustedBy />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
