import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Landing from "../components/landing";
import Aboutus from "../components/aboutus";
import Skills from "../components/skills";
import Works from "../components/works";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>khao | ecom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <Aboutus />
      <Skills />
      <Works />
      <Aboutus />
    </div>
  );
};

export default Home;
